version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: catmessager-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
    environment:
      - RABBITMQ_DEFAULT_USER=minecraft
      - RABBITMQ_DEFAULT_PASS=CatMessenger-Adapter
      - RABBITMQ_DEFAULT_VHOST=/minecraft
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - catmessenger-net

  catmessenger:
    image: drdocker03/catmessenger-telegram:v0.1.1
    container_name: catmessenger-adapter
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: always
    entrypoint: ["./CatMessenger.Telegram"]
    volumes:
      - ./config.json:/app/config.json:ro
    networks:
      - catmessenger-net

networks:
  catmessenger-net:
    driver: bridge
