# version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      # - "15672:15672"  # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=minecraft
      - RABBITMQ_DEFAULT_PASS=CatMessenger-Adapter
      - RABBITMQ_DEFAULT_VHOST=/minecraft
    networks:
      - catmessenger-net

  catmessenger:
    image: drdocker03/catmessenger-telegram:v0.1.1
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
    restart: always
    entrypoint: ["./CatMessenger.Telegram"]
    volumes:
      - ./config.json:/app/config.json:ro
    networks:
      - catmessenger-net

networks:
  catmessenger-net:
    driver: bridge
