name: Build Docker on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-telegram:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - 
        name: Build and push CatMessenger.Telegram image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          file: CatMessenger.Telegram/Dockerfile
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/catmessenger-telegram:${{ github.ref_name }}

  build-matrix:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - 
        name: Build and push CatMessenger.Matrix image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: CatMessenger.Matrix/Dockerfile
          push: true
          tags: docker.io/${{ vars.DOCKERHUB_USERNAME }}/catmessenger-matrix:${{ github.ref_name }}